export default {
  'en-US': {
    'Welcome to SOFA': 'Welcome to SOFA',
    'Where Your Wealth Flourishes in Fairness and Freedom. <br/>Your Wealth, Your Way: Freedom and Fairness in Every Opportunity.':
      'Where Your Wealth Flourishes in Fairness and Freedom. <br/>Your Wealth, Your Way: Freedom and Fairness in Every Opportunity.',
    'Goodbye Counterparty Risks.<br/>And Good Riddance.':
      'Goodbye Counterparty Risks.<br/>And Good Riddance.',
    'Trade with whoever you want, whatever you want.<br/>Know your assets are always safe on-chain.':
      'Trade with whoever you want, whatever you want.<br/>Know your assets are always safe on-chain.',
    'Imagine if the world had a widely available technology solution that provided immutable data records, traceable transactions, definable parameters, operational transparency, and exceptional network security...\n\nSurely a technology like that would provide <span class="txt-gradient">the ideal platform for a decentralized, trustless settlement platform</span> for settling any and all financial transactions, <span class="txt-gradient">regardless of your intermediary</span>?\n<span class="txt-gradient">SOFA.org</span> is here to make that a reality.':
      'Imagine if the world had a widely available technology solution that provided immutable data records, traceable transactions, definable parameters, operational transparency, and exceptional network security...\n\nSurely a technology like that would provide <span class="txt-gradient">the ideal platform for a decentralized, trustless settlement platform</span> for settling any and all financial transactions, <span class="txt-gradient">regardless of your intermediary</span>?\n<span class="txt-gradient">SOFA.org</span> is here to make that a reality.',
    'Blockchain Settlement.<br/>For Real.':
      'Blockchain Settlement.<br/>For Real.',
    'Digital assets demand a critical rethink of our settlement standards.':
      'Digital assets demand a critical rethink of our settlement standards.',
    'Imagine if the world had a widely available technology solution that provided immutable data records, traceable transactions, definable parameters, operational transparency, and exceptional network security...\n\nIt\'s time to stop relying on centralized, off-chain ledgers for recording instrument data, and start putting them on on-chain where they belong.  <span class="txt-gradient">A digitally native asset deserves a digitally native settlement solution</span>, and <span class="txt-gradient">SOFA.org</span> is here with a framework to show the world how it should be done.\n\nSettlement standards have evolved from paper ledgers, to electronic records, and now to the blockchain network.  Progress is as inevitable as the flow of time, so let\'s get the foundation built correctly from the get-go.':
      'Imagine if the world had a widely available technology solution that provided immutable data records, traceable transactions, definable parameters, operational transparency, and exceptional network security...\n\nIt\'s time to stop relying on centralized, off-chain ledgers for recording instrument data, and start putting them on on-chain where they belong.  <span class="txt-gradient">A digitally native asset deserves a digitally native settlement solution</span>, and <span class="txt-gradient">SOFA.org</span> is here with a framework to show the world how it should be done.\n\nSettlement standards have evolved from paper ledgers, to electronic records, and now to the blockchain network.  Progress is as inevitable as the flow of time, so let\'s get the foundation built correctly from the get-go.',
    'Risk Tokenization.<br/>Catalyzing Capital Efficiency in DeFi.':
      'Risk Tokenization.<br/>Catalyzing Capital Efficiency in DeFi.',
    'Providing a secure rehypothecation solution for on-chain assets.':
      'Providing a secure rehypothecation solution for on-chain assets.',
    '"ETFs are step one in the technological revolution in the financial markets. Step two is gonna be the tokenization of every financial asset.” - Blackrock CEO Larry Fink, January 2024\n\nWith everyone now hopping onto the \'tokenize-everything\' bandwagon, the genie is now out of the bottle and with no looking back.  Just as derivatives created significant flexibility over spot instruments, <span class="txt-gradient">tokenization opens up a new dimension of ownership tracking and risk replication that were not possible with conventional methods.</span>\n\nInstead of leaving high-value assets sitting dormant on-chain, surely there are more effective ways to replicate and transfer that unique collateral claim to another?  What if these claims were compatible with conventional tokens standards and accepted by both DeFi and CeFi platforms, and thereby <span class="txt-gradient">unlocking significant capital efficiency and money velocity across the entire crypto system</span>?\n\nOur \'Position Tokens\' adhere to ERC-1155 standards, allowing the creation and management of multiple types of tokens within a single contract, with support for each type of token having different properties.  This adoption <span class="txt-gradient">strikes a careful balance between compatibility, flexibility, and gas efficiency</span>.':
      '"ETFs are step one in the technological revolution in the financial markets. Step two is gonna be the tokenization of every financial asset.” - Blackrock CEO Larry Fink, January 2024\n\nWith everyone now hopping onto the \'tokenize-everything\' bandwagon, the genie is now out of the bottle and with no looking back.  Just as derivatives created significant flexibility over spot instruments, <span class="txt-gradient">tokenization opens up a new dimension of ownership tracking and risk replication that were not possible with conventional methods.</span>\n\nInstead of leaving high-value assets sitting dormant on-chain, surely there are more effective ways to replicate and transfer that unique collateral claim to another?  What if these claims were compatible with conventional tokens standards and accepted by both DeFi and CeFi platforms, and thereby <span class="txt-gradient">unlocking significant capital efficiency and money velocity across the entire crypto system</span>?\n\nOur \'Position Tokens\' adhere to ERC-1155 standards, allowing the creation and management of multiple types of tokens within a single contract, with support for each type of token having different properties.  This adoption <span class="txt-gradient">strikes a careful balance between compatibility, flexibility, and gas efficiency</span>.',
    'Strength in Numbers.<br/>Truth and Transparency.':
      'Strength in Numbers.<br/>Truth and Transparency.',
    'DeFi, CeFi, TradFi - It should be all about the greater ecosystem.':
      'DeFi, CeFi, TradFi - It should be all about the greater ecosystem.',
    'As a decentralized, non-profit, open-source technology organization, <span class="txt-gradient">SOFA.org</span> is a steadfast proponent and supporter of the decentralized and trustless spirit in DeFi.\n\nHowever, let\'s be clear that the <span class="txt-gradient">decentralization spirit should be about promoting user access and participation, rather than absolving responsibility</span> in how we conduct ourselves.  While blockchain executions could be anonymous, it should not be a free-ride to some unrestrained form of financial ararchy, and we are looking to promote <span class="txt-gradient">a set of self-imposed, \'best practices\' guidelines to uphold the collaborative spirit of DeFi</span>.\n\nEvery part of our protocol design, including contract transparency, vault classification, extensibility, and fair-launch tokenomics <span class="txt-gradient">demonstrate our resolve and commitment to building a more responsible DeFi</span>.  We are excited to work hand-in-hand with partners who share in our core values and spirit.  LFG!':
      'As a decentralized, non-profit, open-source technology organization, <span class="txt-gradient">SOFA.org</span> is a steadfast proponent and supporter of the decentralized and trustless spirit in DeFi.\n\nHowever, let\'s be clear that the <span class="txt-gradient">decentralization spirit should be about promoting user access and participation, rather than absolving responsibility</span> in how we conduct ourselves.  While blockchain executions could be anonymous, it should not be a free-ride to some unrestrained form of financial ararchy, and we are looking to promote <span class="txt-gradient">a set of self-imposed, \'best practices\' guidelines to uphold the collaborative spirit of DeFi</span>.\n\nEvery part of our protocol design, including contract transparency, vault classification, extensibility, and fair-launch tokenomics <span class="txt-gradient">demonstrate our resolve and commitment to building a more responsible DeFi</span>.  We are excited to work hand-in-hand with partners who share in our core values and spirit.  LFG!',
    'Fair Launch Tokenomics.<br/>Use-Case Driven Gains.':
      'Fair Launch Tokenomics.<br/>Use-Case Driven Gains.',
    'Building a sustainable model for the long-run.':
      'Building a sustainable model for the long-run.',
    'Unlike the majority of projects, our <span class="txt-gradient">protocol tokenomics will adopt a 100% fair launch model</span>, so no one - not the team, not VCs, not specialized privileged groups - will have ownership of any utility tokens at launch.  It\'s almost like Bitcoin circa-2010 all over again!.\n\n<span class="txt-gradient">Utility tokens can only be earned via airdrops as a participating user of the protocol, or as a contributing community building member</span>.  The rest of the (capped) float will be left in a standard Uniswap AMM pool, with and a hard cap on the total issuance from day 1.\n\nFurthermore, <span class="txt-gradient">100% of the protocol\'s earnings will be used to burn our native tokens daily, ensuring a long-term deflationary token float</span> and aligning all value accretion back to our core users (and hodlers).\n\nThe higher the protocol-use, the greater the fees, triggering more token buybacks.  A sustainable, use-case driven model built for the long-run.  Stay long-term greedy.':
      'Unlike the majority of projects, our <span class="txt-gradient">protocol tokenomics will adopt a 100% fair launch model</span>, so no one - not the team, not VCs, not specialized privileged groups - will have ownership of any utility tokens at launch.  It\'s almost like Bitcoin circa-2010 all over again!.\n\n<span class="txt-gradient">Utility tokens can only be earned via airdrops as a participating user of the protocol, or as a contributing community building member</span>.  The rest of the (capped) float will be left in a standard Uniswap AMM pool, with and a hard cap on the total issuance from day 1.\n\nFurthermore, <span class="txt-gradient">100% of the protocol\'s earnings will be used to burn our native tokens daily, ensuring a long-term deflationary token float</span> and aligning all value accretion back to our core users (and hodlers).\n\nThe higher the protocol-use, the greater the fees, triggering more token buybacks.  A sustainable, use-case driven model built for the long-run.  Stay long-term greedy.',
  },
  'ja-JP': {
    'Goodbye Counterparty Risks.<br/>And Good Riddance.':
      'さようなら対当取リスク。<br/>二度と戻ることはない。',
    'Trade with whoever you want, whatever you want.<br/>Know your assets are always safe on-chain.':
      '好きな人と好きな取引を。<br/>あなたの資産は常にチェーン上で安全です。',
    'Imagine if the world had a widely available technology solution that provided immutable data records, traceable transactions, definable parameters, operational transparency, and exceptional network security...\n\nSurely a technology like that would provide <span class="txt-gradient">the ideal platform for a decentralized, trustless settlement platform</span> for settling any and all financial transactions, <span class="txt-gradient">regardless of your intermediary</span>?\n<span class="txt-gradient">SOFA.org</span> is here to make that a reality.':
      'もし世界に不変のデータ記録や追跡可能な取引、定義可能なパラメーター、運用の透明性、そして優れたネットワークセキュリティを提供する広く利用可能な技術ソリューションが存在したら...\n\nそのような技術は、すべての金融取引を解決するための<span class="txt-gradient">理想的な分散型、信用のいらない決済プラットフォーム</span>を提供するでしょう。<span class="txt-gradient">仲介者に関係なく</span>。<span class="txt-gradient">SOFA.org</span>がそれを実現します。',
    'Blockchain Settlement.<br/>For Real.':
      'ブロックチェーンによる決済。<br/>まさに本物。',
    'Digital assets demand a critical rethink of our settlement standards.':
      'デジタル資産は、私たちの決済基準を根本から再考することを要求しています。',
    'Imagine if the world had a widely available technology solution that provided immutable data records, traceable transactions, definable parameters, operational transparency, and exceptional network security...\n\nIt\'s time to stop relying on centralized, off-chain ledgers for recording instrument data, and start putting them on on-chain where they belong.  <span class="txt-gradient">A digitally native asset deserves a digitally native settlement solution</span>, and <span class="txt-gradient">SOFA.org</span> is here with a framework to show the world how it should be done.\n\nSettlement standards have evolved from paper ledgers, to electronic records, and now to the blockchain network.  Progress is as inevitable as the flow of time, so let\'s get the foundation built correctly from the get-go.':
      'もし世界に広く利用可能な技術ソリューションがあり、不変のデータ記録、追跡可能な取引、定義可能なパラメータ、運用の透明性、そして卓越したネットワークセキュリティを提供していたら...\n\n中央集権的なオフチェーン台帳に依存するのを止め、本来あるべきオンチェーンにデータを置き始める時が来ました。<span class="txt-gradient">デジタルネイティブ資産にはデジタルネイティブな決済ソリューションが必要です</span>。<span class="txt-gradient">SOFA.org</span>が正しいやり方を世界に示すためのフレームワークを提供します。',
    'Risk Tokenization.<br/>Catalyzing Capital Efficiency in DeFi.':
      'リスクトークン化。<br/>DeFiでの資本効率を促進。',
    'Providing a secure rehypothecation solution for on-chain assets.':
      'チェーン上の資産に対して安全な再担保ソリューションを提供します。',
    '"ETFs are step one in the technological revolution in the financial markets. Step two is gonna be the tokenization of every financial asset.” - Blackrock CEO Larry Fink, January 2024\n\nWith everyone now hopping onto the \'tokenize-everything\' bandwagon, the genie is now out of the bottle and with no looking back.  Just as derivatives created significant flexibility over spot instruments, <span class="txt-gradient">tokenization opens up a new dimension of ownership tracking and risk replication that were not possible with conventional methods.</span>\n\nInstead of leaving high-value assets sitting dormant on-chain, surely there are more effective ways to replicate and transfer that unique collateral claim to another?  What if these claims were compatible with conventional tokens standards and accepted by both DeFi and CeFi platforms, and thereby <span class="txt-gradient">unlocking significant capital efficiency and money velocity across the entire crypto system</span>?\n\nOur \'Position Tokens\' adhere to ERC-1155 standards, allowing the creation and management of multiple types of tokens within a single contract, with support for each type of token having different properties.  This adoption <span class="txt-gradient">strikes a careful balance between compatibility, flexibility, and gas efficiency</span>.':
      '"ETFは金融市場の技術革新の第一歩です。次のステップはすべての金融資産のトークン化になるでしょう。" - ブラックロックのCEOラリー・フィンク 2024年1月\n\n今やすべてをトークン化する流れにみんなが飛び乗っていて、もう後戻りはできません。衍生商品がスポット取引よりも大きな柔軟性を生み出したように、<span class="txt-gradient">トークン化は従来の方法では不可能だった所有権追跡とリスク複製の新しい次元を開きます</span>。\n\n高価な資産をチェーン上で放置する代わりに、そのユニークな担保請求を効果的に複製し、他者に移転する方法があるはずです。もしこれらの請求が従来のトークン基準と互換性があり，DeFiおよびCeFiプラットフォームの両方によって受け入れられたら，<span class="txt-gradient">それにより暗号システム全体にわたる資本効率と貨幣の流通速度を顕著に開放することになります</span>。\n\n私たちの「ポジション・トークン」は ERC-1155 規格に準拠し、単一の契約内で複数タイプのトークンを作成・管理することができます。',
    'Strength in Numbers.<br/>Truth and Transparency.':
      '団結は力なり。<br/>真実と透明性。',
    'DeFi, CeFi, TradFi - It should be all about the greater ecosystem.':
      'DeFi、CeFi、TradFi - すべてはより大きな生態系に関するものです。',
    'As a decentralized, non-profit, open-source technology organization, <span class="txt-gradient">SOFA.org</span> is a steadfast proponent and supporter of the decentralized and trustless spirit in DeFi.\n\nHowever, let\'s be clear that the <span class="txt-gradient">decentralization spirit should be about promoting user access and participation, rather than absolving responsibility</span> in how we conduct ourselves.  While blockchain executions could be anonymous, it should not be a free-ride to some unrestrained form of financial ararchy, and we are looking to promote <span class="txt-gradient">a set of self-imposed, \'best practices\' guidelines to uphold the collaborative spirit of DeFi</span>.\n\nEvery part of our protocol design, including contract transparency, vault classification, extensibility, and fair-launch tokenomics <span class="txt-gradient">demonstrate our resolve and commitment to building a more responsible DeFi</span>.  We are excited to work hand-in-hand with partners who share in our core values and spirit.  LFG!':
      '<span class="txt-gradient">SOFA.org</span>は、非集中型で非営利のオープンソースの技術組織として、DeFi内の非集中型かつ信用の不要な精神',
    'Fair Launch Tokenomics.<br/>Use-Case Driven Gains.':
      '公平な立ち上げトークンエコノミー。<br/>ユースケース主導の利益。',
    'Building a sustainable model for the long-run.':
      '長期的に持続可能なモデルを構築中。',
    'Unlike the majority of projects, our <span class="txt-gradient">protocol tokenomics will adopt a 100% fair launch model</span>, so no one - not the team, not VCs, not specialized privileged groups - will have ownership of any utility tokens at launch.  It\'s almost like Bitcoin circa-2010 all over again!.\n\n<span class="txt-gradient">Utility tokens can only be earned via airdrops as a participating user of the protocol, or as a contributing community building member</span>.  The rest of the (capped) float will be left in a standard Uniswap AMM pool, with and a hard cap on the total issuance from day 1.\n\nFurthermore, <span class="txt-gradient">100% of the protocol\'s earnings will be used to burn our native tokens daily, ensuring a long-term deflationary token float</span> and aligning all value accretion back to our core users (and hodlers).\n\nThe higher the protocol-use, the greater the fees, triggering more token buybacks.  A sustainable, use-case driven model built for the long-run.  Stay long-term greedy.':
      '多数のプロジェクトと異なり、私たちの<span class="txt-gradient">プロトコルのトークンエコノミーは100%公平なローンチモデルを採用します。</span>従って、チームもVCも特権を持つグループも、ローンチ時には何のトークンも所有していません。これはまるで2010年ごろのビットコインの再来のようです！',
    'Welcome to SOFA': 'SOFAへようこそ',
    'Where Your Wealth Flourishes in Fairness and Freedom. <br/>Your Wealth, Your Way: Freedom and Fairness in Every Opportunity.':
      '公平と自由のもとであなたの富が花開く場所。<br/>あなたの富、あなたの方法：すべての機会において自由と公正。',
  },
  'ru-RU': {
    'Goodbye Counterparty Risks.<br/>And Good Riddance.':
      'Прощайте контрагентские риски.<br/>И это навсегда.',
    'Trade with whoever you want, whatever you want.<br/>Know your assets are always safe on-chain.':
      'Торгуйте с кем угодно, что угодно.<br/>Знайте, что ваши активы всегда в безопасности на блокчейне.',
    'Imagine if the world had a widely available technology solution that provided immutable data records, traceable transactions, definable parameters, operational transparency, and exceptional network security...\n\nSurely a technology like that would provide <span class="txt-gradient">the ideal platform for a decentralized, trustless settlement platform</span> for settling any and all financial transactions, <span class="txt-gradient">regardless of your intermediary</span>?\n<span class="txt-gradient">SOFA.org</span> is here to make that a reality.':
      'Представьте, что в мире есть широкодоступное технологическое решение, обеспечивающее неизменные записи данных, прослеживаемые транзакции, определяемые параметры, операционную прозрачность и выдающуюся сетевую безопасность...\n\nКонечно, технология подобного рода обеспечила бы <span class="txt-gradient">идеальную платформу для децентрализованной, бездоверительной платформы расчетов</span> для всех финансовых транзакций, <span class="txt-gradient">независимо от посредников</span>.\n<span class="txt-gradient">SOFA.org</span> создана, чтобы сделать это реальностью.',
    'Blockchain Settlement.<br/>For Real.':
      'Блокчейн-расчеты.<br/>На самом деле.',
    'Digital assets demand a critical rethink of our settlement standards.':
      'Цифровые активы требуют критического переосмысления наших стандартов расчетов.',
    'Imagine if the world had a widely available technology solution that provided immutable data records, traceable transactions, definable parameters, operational transparency, and exceptional network security...\n\nIt\'s time to stop relying on centralized, off-chain ledgers for recording instrument data, and start putting them on on-chain where they belong.  <span class="txt-gradient">A digitally native asset deserves a digitally native settlement solution</span>, and <span class="txt-gradient">SOFA.org</span> is here with a framework to show the world how it should be done.\n\nSettlement standards have evolved from paper ledgers, to electronic records, and now to the blockchain network.  Progress is as inevitable as the flow of time, so let\'s get the foundation built correctly from the get-go.':
      'Представьте, что в мире есть широкодоступное технологическое решение, предоставляющее неизменные данные, прослеживаемые транзакции, определяемые параметры, операционную прозрачность и исключительную сетевую безопасность...\n\nПришло время перестать полагаться на централизованные внеблочные журналы для записи данных инструментов и начать размещать их в блокчейне, там где они и должны быть. <span class="txt-gradient">Цифровой актив требует цифрового решения для расчетов</span>, и <span class="txt-gradient">SOFA.org</span> пришла с рамками, чтобы показать миру, как это должно быть выполнено.\n\nСтандарты расчетов эволюционировали от бумажных книг до электронных записей и теперь до сети блокчейн. Прогресс неизбежен, как течение времени, поэтому давайте правильно построим основу с самого начала.',
    'Risk Tokenization.<br/>Catalyzing Capital Efficiency in DeFi.':
      'Токенизация риска.<br/>Стимулирование эффективности капитала в DeFi.',
    'Providing a secure rehypothecation solution for on-chain assets.':
      'Обеспечение безопасного решения перезалога для активов на блокчейне.',
    '"ETFs are step one in the technological revolution in the financial markets. Step two is gonna be the tokenization of every financial asset.” - Blackrock CEO Larry Fink, January 2024\n\nWith everyone now hopping onto the \'tokenize-everything\' bandwagon, the genie is now out of the bottle and with no looking back.  Just as derivatives created significant flexibility over spot instruments, <span class="txt-gradient">tokenization opens up a new dimension of ownership tracking and risk replication that were not possible with conventional methods.</span>\n\nInstead of leaving high-value assets sitting dormant on-chain, surely there are more effective ways to replicate and transfer that unique collateral claim to another?  What if these claims were compatible with conventional tokens standards and accepted by both DeFi and CeFi platforms, and thereby <span class="txt-gradient">unlocking significant capital efficiency and money velocity across the entire crypto system</span>?\n\nOur \'Position Tokens\' adhere to ERC-1155 standards, allowing the creation and management of multiple types of tokens within a single contract, with support for each type of token having different properties.  This adoption <span class="txt-gradient">strikes a careful balance between compatibility, flexibility, and gas efficiency</span>.':
      '"ETF - это первый шаг в технологической революции на финансовых рынках. Вторым шагом будет токенизация каждого финансового актива." - Главный исполнительный директор Blackrock Ларри Финк, январь 2024 года\n\nТеперь, когда все присоединились к движению \'токенизации всего\', джин вышел из бутылки и пути назад нет. Так же, как производные создали значительную гибкость по сравнению с мгновенными инструментами, <span class="txt-gradient">токенизация открывает новое измерение отслеживания владения и воспроизводства рисков, которые были невозможны традиционными методами.</span>\n\nВместо того, чтобы оставлять высокоценные активы неактивными в блокчейне, разве нет более эффективных способов воспроизводить и передавать это уникальное залоговое требование другому? Что если эти требования будут совместимы со стандартами обычных токенов и приняты как платформами DeFi, так и CeFi, тем самым <span class="txt-gradient">освобождая значительную эффективность капитала и скорость денег по всей криптосистеме</span>?\n\nНаши \'Позиционные токены\' соответствуют стандартам ERC-1155, позволяя создание и управление множеством типов токенов в одном контракте, каждый тип токена обладает различными свойствами. Это внедрение <span class="txt-gradient">достигает осторожного баланса между совместимостью, гибкостью и эффективностью использования газа</span>.',
    'Strength in Numbers.<br/>Truth and Transparency.':
      'Сила в численности.<br/>Правда и прозрачность.',
    'DeFi, CeFi, TradFi - It should be all about the greater ecosystem.':
      'DeFi, CeFi, TradFi - Это должно быть о большой экосистеме.',
    'As a decentralized, non-profit, open-source technology organization, <span class="txt-gradient">SOFA.org</span> is a steadfast proponent and supporter of the decentralized and trustless spirit in DeFi.\n\nHowever, let\'s be clear that the <span class="txt-gradient">decentralization spirit should be about promoting user access and participation, rather than absolving responsibility</span> in how we conduct ourselves.  While blockchain executions could be anonymous, it should not be a free-ride to some unrestrained form of financial ararchy, and we are looking to promote <span class="txt-gradient">a set of self-imposed, \'best practices\' guidelines to uphold the collaborative spirit of DeFi</span>.\n\nEvery part of our protocol design, including contract transparency, vault classification, extensibility, and fair-launch tokenomics <span class="txt-gradient">demonstrate our resolve and commitment to building a more responsible DeFi</span>.  We are excited to work hand-in-hand with partners who share in our core values and spirit.  LFG!':
      'Как децентрализованная, некоммерческая, открытая технологическая организация, <span class="txt-gradient">SOFA.org</span> является непоколебимым сторонником и поддерживает бездоверительный дух в DeFi.\n\nОднако давайте будем четкими: <span class="txt-gradient">дух децентрализации должен способствовать доступу и участию пользователей, а не освобождению от ответственности</span> за наше поведение. Хотя исполнения блокчейна могут быть анонимными, это не должно быть бесплатным проездом к какой-то неограниченной форме финансовой анархии, и мы стремимся продвигать <span class="txt-gradient">набор самонавязанных \'лучших практик\' для поддержания совместного духа DeFi</span>.\n\nКаждый элемент нашего дизайна протокола, включая прозрачность контрактов, классификацию хранилищ, расширяемость и справедливые стартовые токеномики <span class="txt-gradient">демонстрируют нашу решимость и обязательства по созданию более ответственного DeFi</span>. Мы рады работать рука об руку с партнерами, которые разделяют наши основные ценности и дух. Вперед!',
    'Fair Launch Tokenomics.<br/>Use-Case Driven Gains.':
      'Справедливые стартовые токеномики.<br/>Прибыль, основанная на использовании.',
    'Building a sustainable model for the long-run.':
      'Создание устойчивой модели на долгосрочную перспективу.',
    'Unlike the majority of projects, our <span class="txt-gradient">protocol tokenomics will adopt a 100% fair launch model</span>, so no one - not the team, not VCs, not specialized privileged groups - will have ownership of any utility tokens at launch.  It\'s almost like Bitcoin circa-2010 all over again!.\n\n<span class="txt-gradient">Utility tokens can only be earned via airdrops as a participating user of the protocol, or as a contributing community building member</span>.  The rest of the (capped) float will be left in a standard Uniswap AMM pool, with and a hard cap on the total issuance from day 1.\n\nFurthermore, <span class="txt-gradient">100% of the protocol\'s earnings will be used to burn our native tokens daily, ensuring a long-term deflationary token float</span> and aligning all value accretion back to our core users (and hodlers).\n\nThe higher the protocol-use, the greater the fees, triggering more token buybacks.  A sustainable, use-case driven model built for the long-run.  Stay long-term greedy.':
      'В отличие от большинства проектов, наша <span class="txt-gradient">токеномика протокола примет модель 100% честного запуска</span>, так что никто - ни команда, ни венчурные капиталисты, ни специализированные привилегированные группы - не будет иметь владения какими-либо функциональными токенами при запуске. Это почти как повторение Bitcoin около 2010 года!\n\n<span class="txt-gradient">Функциональные токены можно заработать только через airdrops как участнику протокола или как члену сообщества</span>. Остальная часть (ограниченного) плавающего запаса будет оставлена в стандартном пуле Uniswap AMM, с жесткой крышкой на общий выпуск с первого дня.\n\nКроме того, <span class="txt-gradient">100% доходов протокола будут использоваться для ежедневного сожжения наших коренных токенов, обеспечивая долгосрочную дефляционную плавучесть токенов</span> и совмещая все приращение ценности обратно нашим основным пользователям (и ходлерам).\n\nЧем выше использование протокола, тем больше сборов, что вызывает больше выкупа токенов. Устойчивая, ориентированная на использование модель, построенная на долгосрочную перспективу. Будьте жадными на долгосрочную перспективу.',
    'Welcome to SOFA': 'Добро пожаловать в SOFA',
    'Where Your Wealth Flourishes in Fairness and Freedom. <br/>Your Wealth, Your Way: Freedom and Fairness in Every Opportunity.':
      'Где ваше богатство процветает в справедливости и свободе. <br/>Ваше богатство, ваш путь: свобода и справедливость в каждой возможности.',
  },
  'zh-CN': {
    'Welcome to SOFA': '欢迎来到SOFA',
    'Where Your Wealth Flourishes in Fairness and Freedom. <br/>Your Wealth, Your Way: Freedom and Fairness in Every Opportunity.':
      '在公平与自由中让您的财富茁壮成长。<br/>您的财富，您的方式：公平自由，尽在每次机遇。',
    'Goodbye Counterparty Risks.<br/>And Good Riddance.':
      '再见对手方风险。<br/>一去不复返。',
    'Trade with whoever you want, whatever you want.<br/>Know your assets are always safe on-chain.':
      '与任何人交易任何资产。<br/>放心，您的资产始终安全地保存在链上。',
    'Imagine if the world had a widely available technology solution that provided immutable data records, traceable transactions, definable parameters, operational transparency, and exceptional network security...\n\nSurely a technology like that would provide <span class="txt-gradient">the ideal platform for a decentralized, trustless settlement platform</span> for settling any and all financial transactions, <span class="txt-gradient">regardless of your intermediary</span>?\n<span class="txt-gradient">SOFA.org</span> is here to make that a reality.':
      '想象一下，如果世界上有一种广泛可用的技术解决方案，可以提供不可更改的数据记录、可追踪的交易、可定义的参数、操作透明和卓越的网络安全……\n\n毫无疑问，这样的技术将成为<spann class=""txt-gradient"">去中心化、无信任结算平台</span>的理想基础，用于结算任何和所有的金融交易，<span class=""txt-gradient"">无论您使用何种中介</span>。 <span class=""txt-gradient"">SOFA.org</span>就是为此而生的。”',
    'Blockchain Settlement.<br/>For Real.': '区块链结算。<br/>真实发生。',
    'Digital assets demand a critical rethink of our settlement standards.':
      '数字资产需要我们重新审视结算标准。',
    'Imagine if the world had a widely available technology solution that provided immutable data records, traceable transactions, definable parameters, operational transparency, and exceptional network security...\n\nIt\'s time to stop relying on centralized, off-chain ledgers for recording instrument data, and start putting them on on-chain where they belong.  <span class="txt-gradient">A digitally native asset deserves a digitally native settlement solution</span>, and <span class="txt-gradient">SOFA.org</span> is here with a framework to show the world how it should be done.\n\nSettlement standards have evolved from paper ledgers, to electronic records, and now to the blockchain network.  Progress is as inevitable as the flow of time, so let\'s get the foundation built correctly from the get-go.':
      '想象一下，如果世界上有一种广泛可用的技术解决方案，可以提供不可更改的数据记录、可追踪的交易、可定义的参数、操作透明和卓越的网络安全……\n\n是时候停止依赖中心化的链下账本来记录金融工具数据，而应将它们放在应属于它们的链上。 <span class="txt-gradient">数字原生资产需要数字原生的结算解决方案</span>，<span class="txt-gradient">SOFA.org</span>带来了一个框架，向世界展示如何正确实现这一目标。\n\n结算标准已经从纸质账本，发展到电子记录，再到现在的区块链网络。进步就像时间的流逝一样不可避免，所以让我们从一开始就正确构建基础。”',
    'Risk Tokenization.<br/>Catalyzing Capital Efficiency in DeFi.':
      '风险代币化。<br/>推动DeFi中的资本效率。',
    'Providing a secure rehypothecation solution for on-chain assets.':
      '为链上资产提供一个安全的再抵押解决方案。',
    '"ETFs are step one in the technological revolution in the financial markets. Step two is gonna be the tokenization of every financial asset.” - Blackrock CEO Larry Fink, January 2024\n\nWith everyone now hopping onto the \'tokenize-everything\' bandwagon, the genie is now out of the bottle and with no looking back.  Just as derivatives created significant flexibility over spot instruments, <span class="txt-gradient">tokenization opens up a new dimension of ownership tracking and risk replication that were not possible with conventional methods.</span>\n\nInstead of leaving high-value assets sitting dormant on-chain, surely there are more effective ways to replicate and transfer that unique collateral claim to another?  What if these claims were compatible with conventional tokens standards and accepted by both DeFi and CeFi platforms, and thereby <span class="txt-gradient">unlocking significant capital efficiency and money velocity across the entire crypto system</span>?\n\nOur \'Position Tokens\' adhere to ERC-1155 standards, allowing the creation and management of multiple types of tokens within a single contract, with support for each type of token having different properties.  This adoption <span class="txt-gradient">strikes a careful balance between compatibility, flexibility, and gas efficiency</span>.':
      '“ETF是金融市场技术革命的第一步。第二步将是每一个金融资产的代币化。”——贝莱德CEO拉里·芬克，2024年1月\n\n如今，大家都在追随“万物代币化”的潮流，魔法已然施展，无法回头。就像衍生品为现货工具带来了巨大的灵活性一样，，<span class="txt-gradient">代币化开启了所有权追踪和风险复制新维度，这是传统方法无法实现的。</span>\n\n与其让高价值资产在链上闲置，不如寻找更有效的方法来复制和转移这种独特的抵押权益？如果这些权利与传统的代币标准兼容并被DeFi和CeFi平台接受，从而<span class="txt-gradient">释放整个加密系统中的资本效率和货币流通速度，那将如何？</span>？\n\n我们的\'头寸代币\'遵循ERC-1155标准，允许在单一合约中创建和管理多种类型的代币，每种代币都有不同的属性。这个采用<span class="txt-gradient">在兼容性、灵活性和Gas效率之间找到了一个谨慎的平衡。</span>',
    'Strength in Numbers.<br/>Truth and Transparency.':
      '人多力量大。<br/>真理与透明。',
    'DeFi, CeFi, TradFi - It should be all about the greater ecosystem.':
      'DeFi、CeFi、TradFi - 应该是关于更大生态系统的一切。',
    'As a decentralized, non-profit, open-source technology organization, <span class="txt-gradient">SOFA.org</span> is a steadfast proponent and supporter of the decentralized and trustless spirit in DeFi.\n\nHowever, let\'s be clear that the <span class="txt-gradient">decentralization spirit should be about promoting user access and participation, rather than absolving responsibility</span> in how we conduct ourselves.  While blockchain executions could be anonymous, it should not be a free-ride to some unrestrained form of financial ararchy, and we are looking to promote <span class="txt-gradient">a set of self-imposed, \'best practices\' guidelines to uphold the collaborative spirit of DeFi</span>.\n\nEvery part of our protocol design, including contract transparency, vault classification, extensibility, and fair-launch tokenomics <span class="txt-gradient">demonstrate our resolve and commitment to building a more responsible DeFi</span>.  We are excited to work hand-in-hand with partners who share in our core values and spirit.  LFG!':
      '作为一个去中心化的非营利开源技术组织，<span class="txt-gradient">SOFA.org</span>是DeFi去中心化和无需信任精神的坚定支持者和倡导者。\n\n然而，我们要清楚，<span class="txt-gradient">去中心化精神应该是关于促进用户访问和参与，而不是在我们的行为中逃避责任</span>。虽然区块链执行可能是匿名的，但它不应该是某种不受约束的金融无政府状态的免费通行证，我们致力于推广一套自我约束的\'最佳实践\'准则，以维护DeFi的协作精神<span class="txt-gradient">。</span>\n\n我们协议设计的每一个部分，包括合约透明度、金库分类、可扩展性和公平启动代币经济 <span class="txt-gradient">都展示了我们建设更负责任的DeFi的决心和承诺</span>。我们非常期待与那些与我们共享核心价值观和精神的合作伙伴携手共进。LFG！',
    'Fair Launch Tokenomics.<br/>Use-Case Driven Gains.':
      '公平启动代币经济学。<br/>基于实际应用的收益。',
    'Building a sustainable model for the long-run.': '为长期建立可持续模型。',
    'Unlike the majority of projects, our <span class="txt-gradient">protocol tokenomics will adopt a 100% fair launch model</span>, so no one - not the team, not VCs, not specialized privileged groups - will have ownership of any utility tokens at launch.  It\'s almost like Bitcoin circa-2010 all over again!.\n\n<span class="txt-gradient">Utility tokens can only be earned via airdrops as a participating user of the protocol, or as a contributing community building member</span>.  The rest of the (capped) float will be left in a standard Uniswap AMM pool, with and a hard cap on the total issuance from day 1.\n\nFurthermore, <span class="txt-gradient">100% of the protocol\'s earnings will be used to burn our native tokens daily, ensuring a long-term deflationary token float</span> and aligning all value accretion back to our core users (and hodlers).\n\nThe higher the protocol-use, the greater the fees, triggering more token buybacks.  A sustainable, use-case driven model built for the long-run.  Stay long-term greedy.':
      '与大多数项目不同，我们的<span class="txt-gradient">协议代币经济将采用100%公平启动模式</span>，因此没有人——无论是团队、风投还是特权群体——在启动时拥有任何功能性代币。这几乎就像2010年的比特币重现！\n\n<span class="txt-gradient">经济代币只有成为协议的参与用户或社区建设的贡献者，透过空投才能获得，</span>。其余的（有限）流通代币将保留在标准的Uniswap AMM池中，经济代币在发行的第一天就设定了总发行量的上限。\n\n此外，<span class="txt-gradient">协议的100%收益将用于每日销毁原生经济代币，确保长期的通缩代币流通量，</span>并将所有价值增益回馈给我们的核心用户（和持有者）。\n\n协议使用率越高，手续费越多，从而触发更多的代币回购。这是一个为长期构建的、可持续的、以实际应用为驱动的模型。 坚持长期利益最大化。',
  },
  'zh-HK': {
    'Goodbye Counterparty Risks.<br/>And Good Riddance.':
      '再見對手風險。<br/>一去不復返。',
    'Trade with whoever you want, whatever you want.<br/>Know your assets are always safe on-chain.':
      '與任何人交易任何資產。<br/>放心，您的資產始終安全地保存在鏈上。',
    'Imagine if the world had a widely available technology solution that provided immutable data records, traceable transactions, definable parameters, operational transparency, and exceptional network security...\n\nSurely a technology like that would provide <span class="txt-gradient">the ideal platform for a decentralized, trustless settlement platform</span> for settling any and all financial transactions, <span class="txt-gradient">regardless of your intermediary</span>?\n<span class="txt-gradient">SOFA.org</span> is here to make that a reality.':
      '想象一下，如果世界上有一種廣泛可用的技術解決方案，可以提供不可更改的數據記錄、可追蹤的交易、可定義的參數、操作透明和卓越的網絡安全……\n\n毫無疑問，這樣的技術將成爲<span class="txt-gradient">去中心化、無需信任結算平台</span>的理想基礎，用於結算任何和所有的金融交易，<span class="txt-gradient">無論您使用何種中介</span>。<span class="txt-gradient">SOFA.org</span>就是爲此而生的。',
    'Blockchain Settlement.<br/>For Real.': '區塊鏈結算。<br/>真實發生。',
    'Digital assets demand a critical rethink of our settlement standards.':
      '數字資產需要我們重新審視結算標準。',
    'Imagine if the world had a widely available technology solution that provided immutable data records, traceable transactions, definable parameters, operational transparency, and exceptional network security...\n\nIt\'s time to stop relying on centralized, off-chain ledgers for recording instrument data, and start putting them on on-chain where they belong.  <span class="txt-gradient">A digitally native asset deserves a digitally native settlement solution</span>, and <span class="txt-gradient">SOFA.org</span> is here with a framework to show the world how it should be done.\n\nSettlement standards have evolved from paper ledgers, to electronic records, and now to the blockchain network.  Progress is as inevitable as the flow of time, so let\'s get the foundation built correctly from the get-go.':
      '想象一下，如果世界上有一種廣泛可用的技術解決方案，可以提供不可更改的數據記錄、可追蹤的交易、可定義的參數、操作透明和卓越的網絡安全……\n\n是時候停止依賴中心化的鏈下賬本來記錄金融工具數據，而應將它們放在應屬於它們的鏈上。<span class="txt-gradient">數字原生資產需要數字原生的結算解決方案</span>，<span class="txt-gradient">SOFA.org</span>帶來了一個框架，向世界展示如何正確實現這一目標。\n\n結算標準已經從紙質賬本，發展到電子記錄，再到現在的區塊鏈網絡。進步就像時間的流逝一樣不可避免，所以讓我們從一開始就正確構建基礎。',
    'Risk Tokenization.<br/>Catalyzing Capital Efficiency in DeFi.':
      '風險代幣化。<br/>推動DeFi中的資本效率。',
    'Providing a secure rehypothecation solution for on-chain assets.':
      '爲鏈上資產提供一個安全的再抵押解決方案。',
    '"ETFs are step one in the technological revolution in the financial markets. Step two is gonna be the tokenization of every financial asset.” - Blackrock CEO Larry Fink, January 2024\n\nWith everyone now hopping onto the \'tokenize-everything\' bandwagon, the genie is now out of the bottle and with no looking back.  Just as derivatives created significant flexibility over spot instruments, <span class="txt-gradient">tokenization opens up a new dimension of ownership tracking and risk replication that were not possible with conventional methods.</span>\n\nInstead of leaving high-value assets sitting dormant on-chain, surely there are more effective ways to replicate and transfer that unique collateral claim to another?  What if these claims were compatible with conventional tokens standards and accepted by both DeFi and CeFi platforms, and thereby <span class="txt-gradient">unlocking significant capital efficiency and money velocity across the entire crypto system</span>?\n\nOur \'Position Tokens\' adhere to ERC-1155 standards, allowing the creation and management of multiple types of tokens within a single contract, with support for each type of token having different properties.  This adoption <span class="txt-gradient">strikes a careful balance between compatibility, flexibility, and gas efficiency</span>.':
      '“ETF是金融市場技術革命的第一步。第二步將是每一個金融資產的代幷化。”——貝萊德CEO拉里・芬克，2024年1月\n\n如今，大家都在追隨“萬物代幣化”的潮流，魔法已然施展，無法回頭。就像衍生品爲現貨工具帶來了巨大的靈活性一樣，<span class="txt-gradient">代幣化開啓了所有權追踪和風險複製新維度，這是傳統方法無法實現的。</span>\n\n與其讓高價值資產在鏈上閒置，不如尋找更有效的方法來複製和轉移這種獨特的抵押權益？如果這些權利與傳統的代幣標準兼容並被DeFi和CeFi平台接受，從而<span class="txt-gradient">釋放整個加密系統中的資本效率和貨幣流通速度，那將如何？</span>？\n\n我們的\'頭寸代幣\'遵循ERC-1155標準，允許在單一合約中創建和管理多種類型的代幣，每種代幣都有不同的屬性。這個採用<span class="txt-gradient">在兼容性、靈活性和Gas效率之間找到了一個謹慎的平衡。</span>',
    'Strength in Numbers.<br/>Truth and Transparency.':
      '人多力量大。<br/>真理與透明。',
    'DeFi, CeFi, TradFi - It should be all about the greater ecosystem.':
      'DeFi、CeFi、TradFi - 應該是關於更大生態系統的一切。',
    'As a decentralized, non-profit, open-source technology organization, <span class="txt-gradient">SOFA.org</span> is a steadfast proponent and supporter of the decentralized and trustless spirit in DeFi.\n\nHowever, let\'s be clear that the <span class="txt-gradient">decentralization spirit should be about promoting user access and participation, rather than absolving responsibility</span> in how we conduct ourselves.  While blockchain executions could be anonymous, it should not be a free-ride to some unrestrained form of financial ararchy, and we are looking to promote <span class="txt-gradient">a set of self-imposed, \'best practices\' guidelines to uphold the collaborative spirit of DeFi</span>.\n\nEvery part of our protocol design, including contract transparency, vault classification, extensibility, and fair-launch tokenomics <span class="txt-gradient">demonstrate our resolve and commitment to building a more responsible DeFi</span>.  We are excited to work hand-in-hand with partners who share in our core values and spirit.  LFG!':
      '作爲一個去中心化的非營利開源技術組織，<span class="txt-gradient">SOFA.org</span>是DeFi去中心化和無需信任精神的堅定支持者和倡導者。\n\n然而，我們要清楚，<span class="txt-gradient">去中心化精神應該是關於促進用戶訪問和參與，而不是在我們的行為中逃避責任</span>。雖然區塊鏈執行可能是匿名的，但它不應該是某種不受約束的金融無政府狀態的免費通行證，我們致力於推廣一套自我約束的\'最佳實踐\'準則，以維護DeFi的協作精神<span class="txt-gradient">。</span>\n\n我們協議設計的每一個部分，包括合約透明度、金庫分類、可擴展性和公平啓動代幣經濟 <span class="txt-gradient">都展示了我們建設更負責任的DeFi的決心和承諾</span>。我們非常期待與那些與我們共享核心價值觀和精神的合作夥伴攜手共進。LFG！',
    'Fair Launch Tokenomics.<br/>Use-Case Driven Gains.':
      '公平啓動代幣經濟學。<br/>基於實際應用的收益。',
    'Building a sustainable model for the long-run.': '爲長期建立可持續模型。',
    'Unlike the majority of projects, our <span class="txt-gradient">protocol tokenomics will adopt a 100% fair launch model</span>, so no one - not the team, not VCs, not specialized privileged groups - will have ownership of any utility tokens at launch.  It\'s almost like Bitcoin circa-2010 all over again!.\n\n<span class="txt-gradient">Utility tokens can only be earned via airdrops as a participating user of the protocol, or as a contributing community building member</span>.  The rest of the (capped) float will be left in a standard Uniswap AMM pool, with and a hard cap on the total issuance from day 1.\n\nFurthermore, <span class="txt-gradient">100% of the protocol\'s earnings will be used to burn our native tokens daily, ensuring a long-term deflationary token float</span> and aligning all value accretion back to our core users (and hodlers).\n\nThe higher the protocol-use, the greater the fees, triggering more token buybacks.  A sustainable, use-case driven model built for the long-run.  Stay long-term greedy.':
      '與大多數項目不同，我們的<span class="txt-gradient">協議代幣經濟將采用100%公平啓動模式</span>，因此沒有人——無論是團隊、風投還是特權群體——在啓動時擁有任何功能性代幣。這幾乎就像2010年的比特幣重現！\n\n<span class="txt-gradient">經濟代幣只有成爲協議的參與用戶或社區建設的貢獻者，透過空投才能獲得，</span>。其餘的（有限）流通代幣將保留在標準的Uniswap AMM池中，經濟代幣在發行的第一天就設定了總發行量的上限。\n\n此外，<span class="txt-gradient">協議的100%收益將用於每日銷毀原生經濟代幣，確保長期的通縮代幣流通量，</span>並將所有價值增益回饋給我們的核心用戶（和持有者）。\n\n協議使用率越高，手續費越多，從而觸發更多的代幣回購。這是一個爲長期構建的、可持續的、以實際應用爲驅動的模型。 堅持長期利益最大化。',
    'Welcome to SOFA': '歡迎來到SOFA',
    'Where Your Wealth Flourishes in Fairness and Freedom. <br/>Your Wealth, Your Way: Freedom and Fairness in Every Opportunity.':
      '在公平與自由中讓您的財富茁壯成長。<br/>您的財富，您的方式：公平自由，盡在每次機遇。',
  },
  'zh-TW': {
    'Goodbye Counterparty Risks.<br/>And Good Riddance.':
      '再見對手風險。<br/>一去不復返。',
    'Trade with whoever you want, whatever you want.<br/>Know your assets are always safe on-chain.':
      '與任何人交易任何資產。<br/>放心，您的資產始終安全地保存在鏈上。',
    'Imagine if the world had a widely available technology solution that provided immutable data records, traceable transactions, definable parameters, operational transparency, and exceptional network security...\n\nSurely a technology like that would provide <span class="txt-gradient">the ideal platform for a decentralized, trustless settlement platform</span> for settling any and all financial transactions, <span class="txt-gradient">regardless of your intermediary</span>?\n<span class="txt-gradient">SOFA.org</span> is here to make that a reality.':
      '想像如果世界上有一種廣泛可用的技術解決方案，提供不可更改的數據記錄、可追蹤的交易、可定義的參數、操作透明度和卓越的網絡安全......\n\n毫無疑問，這樣的技術將為任何和所有金融交易提供一個理想的去中心化、無需信任的結算平台<span class="txt-gradient">，無論您使用何種中介</span>。\n<span class="txt-gradient">SOFA.org</span>就在這裡將其變為現實。',
    'Blockchain Settlement.<br/>For Real.': '區塊鏈結算。<br/>真實發生。',
    'Digital assets demand a critical rethink of our settlement standards.':
      '數字資產要求我們重新思考結算標準。',
    'Imagine if the world had a widely available technology solution that provided immutable data records, traceable transactions, definable parameters, operational transparency, and exceptional network security...\n\nIt\'s time to stop relying on centralized, off-chain ledgers for recording instrument data, and start putting them on on-chain where they belong.  <span class="txt-gradient">A digitally native asset deserves a digitally native settlement solution</span>, and <span class="txt-gradient">SOFA.org</span> is here with a framework to show the world how it should be done.\n\nSettlement standards have evolved from paper ledgers, to electronic records, and now to the blockchain network.  Progress is as inevitable as the flow of time, so let\'s get the foundation built correctly from the get-go.':
      '想像如果世界上有一種廣泛可用的技術解決方案，提供不可更改的數據記錄、可追蹤的交易、可定義的參數、操作透明度和卓越的網絡安全......\n\n是時候停止依賴中心化的鏈外賬本來記錄金融工具數據，而應將其放在應屬於它們的鏈上。<span class="txt-gradient">數字原生資產應配合數字原生結算解決方案</span>，<span class="txt-gradient">SOFA.org</span>帶來一個框架，向世界展示應如何正確做到。\n\n結算標準已從紙質賬本演變成電子記錄，現在又進展到區塊鏈網絡。進步是時間流逝的必然，所以讓我們從一開始就正確構建基礎。',
    'Risk Tokenization.<br/>Catalyzing Capital Efficiency in DeFi.':
      '風險代幣化。<br/>推動DeFi中的資本效率。',
    'Providing a secure rehypothecation solution for on-chain assets.':
      '為鏈上資產提供一個安全的再擔保解決方案。',
    '"ETFs are step one in the technological revolution in the financial markets. Step two is gonna be the tokenization of every financial asset.” - Blackrock CEO Larry Fink, January 2024\n\nWith everyone now hopping onto the \'tokenize-everything\' bandwagon, the genie is now out of the bottle and with no looking back.  Just as derivatives created significant flexibility over spot instruments, <span class="txt-gradient">tokenization opens up a new dimension of ownership tracking and risk replication that were not possible with conventional methods.</span>\n\nInstead of leaving high-value assets sitting dormant on-chain, surely there are more effective ways to replicate and transfer that unique collateral claim to another?  What if these claims were compatible with conventional tokens standards and accepted by both DeFi and CeFi platforms, and thereby <span class="txt-gradient">unlocking significant capital efficiency and money velocity across the entire crypto system</span>?\n\nOur \'Position Tokens\' adhere to ERC-1155 standards, allowing the creation and management of multiple types of tokens within a single contract, with support for each type of token having different properties.  This adoption <span class="txt-gradient">strikes a careful balance between compatibility, flexibility, and gas efficiency</span>.':
      '“ETF是金融市場技術革命的第一步。第二步將是每一個金融資產的代幣化。”——Blackrock CEO Larry Fink，2024年1月\n\n現在，所有人都在加入“代幣化一切”的行列，魔法已放出來，無法回頭。就像衍生品為現貨工具帶來了顯著的靈活性一樣，<span class="txt-gradient">代幣化為擁有權追踪和風險複製開啟了一個新維度，這是傳統方法無法做到的。</span>\n\n與其讓高價值資產在鏈上閒置，不如尋找更有效的方法來複製並將獨特的擔保權利轉移到另一方？如果這些權利與傳統的代ErrorMessageToken標準兼容，並被DeFi和CeFi平臺接受，從而<span class="txt-gradient">在整個加密系統中釋放顯著的資本效率和貨幣流通速度</span>?\n\n我們的\'頭寸代碼\'遵循ERC-1155標準，允許在單一合約中創建和管理多種類型的代碼，每種代碼都有不同的屬性。這種採用<span class="txt-gradient">在兼容性、靈活性和Gas效率之間取得了謹慎的平衡。</span>',
    'Strength in Numbers.<br/>Truth and Transparency.':
      '人多力量大。<br/>真理與透明。',
    'DeFi, CeFi, TradFi - It should be all about the greater ecosystem.':
      'DeFi、CeFi、TradFi - 應該是關於更大生態系統的一切。',
    'As a decentralized, non-profit, open-source technology organization, <span class="txt-gradient">SOFA.org</span> is a steadfast proponent and supporter of the decentralized and trustless spirit in DeFi.\n\nHowever, let\'s be clear that the <span class="txt-gradient">decentralization spirit should be about promoting user access and participation, rather than absolving responsibility</span> in how we conduct ourselves.  While blockchain executions could be anonymous, it should not be a free-ride to some unrestrained form of financial ararchy, and we are looking to promote <span class="txt-gradient">a set of self-imposed, \'best practices\' guidelines to uphold the collaborative spirit of DeFi</span>.\n\nEvery part of our protocol design, including contract transparency, vault classification, extensibility, and fair-launch tokenomics <span class="txt-gradient">demonstrate our resolve and commitment to building a more responsible DeFi</span>.  We are excited to work hand-in-hand with partners who share in our core values and spirit.  LFG!':
      '作為一個去中心化的非營利開源技術組織，<span class="txt-gradient">SOFA.org</span>是DeFi去中心化和無需信任精神的堅定支持者和倡導者。\n\n然而，我們要清楚，<span class="txt-gradient">去中心化精神應該是關於促進用戶訪問和參與，而不是在我們的行為中逃避責任</span>。雖然區塊鏈執行可能是匿名的，但它不應該是某種不受約束的金融無政府狀態的免費通行證，我們致力於推廣一組自我約束的\'最佳實踐\'準則，以維護DeFi的協作精神<span class="txt-gradient">。</span>\n\n我們協議設計的每一部分，包括合約透明度、金庫分類、可擴展性和公平啟動代碼經濟<span class="txt-gradient">都展示了我們建設更負責任的DeFi的決心和承諾</span>。我們非常期待與那些與我們共享核心價值觀和精神的合作夥伴携手共進。LFG！',
    'Fair Launch Tokenomics.<br/>Use-Case Driven Gains.':
      '公平啟動代碼經濟學。<br/>基於實際應用的收益。',
    'Building a sustainable model for the long-run.': '為長期建立可持續模型。',
    'Unlike the majority of projects, our <span class="txt-gradient">protocol tokenomics will adopt a 100% fair launch model</span>, so no one - not the team, not VCs, not specialized privileged groups - will have ownership of any utility tokens at launch.  It\'s almost like Bitcoin circa-2010 all over again!.\n\n<span class="txt-gradient">Utility tokens can only be earned via airdrops as a participating user of the protocol, or as a contributing community building member</span>.  The rest of the (capped) float will be left in a standard Uniswap AMM pool, with and a hard cap on the total issuance from day 1.\n\nFurthermore, <span class="txt-gradient">100% of the protocol\'s earnings will be used to burn our native tokens daily, ensuring a long-term deflationary token float</span> and aligning all value accretion back to our core users (and hodlers).\n\nThe higher the protocol-use, the greater the fees, triggering more token buybacks.  A sustainable, use-case driven model built for the long-run.  Stay long-term greedy.':
      '與大多數項目不同，我們的<span class="txt-gradient">協議代碼經濟將採用100%公平啟動模式</span>，因此沒有人 - 不是團隊，不是風投，也不是特權群體 - 在啟動時擁有任何功能性代碼。這幾乎就像2010年的比特幣重來一次！\n\n<span class="txt-gradient">功能性代碼只能作為協議的參與用戶或社區建設的貢獻者，通過空投獲得</span>。其餘的（有封頂的）流通將保留在標準的Uniswap AMM池中，並且從第一天起對總發行量設定硬上限。\n\n此外，<span class="txt-gradient">協議的100%收益將用於每日燒毀我們的原生代碼，確保長期的通縮代碼流通</span>，並將所有價值增值回歸給我們的核心用戶（和持有者）。\n\n協議的使用率越高，費用越多，觸發更多的代碼回購。這是一個為長期構建的、可持續的、以實際應用為驅動的模型。堅持長期利益最大化。',
    'Welcome to SOFA': '歡迎來到 SOFA',
    'Where Your Wealth Flourishes in Fairness and Freedom. <br/>Your Wealth, Your Way: Freedom and Fairness in Every Opportunity.':
      '在公平與自由中讓您的財富茁壯成長。<br/>您的財富，您的方式：公平自由，儘在每次機遇。',
  },
};
