export default {
  'en-US': {
    'confirm-to-burn.cae2f657407bcc9c793c957b87edf312': 'Confirm to Burn',
    'switch-to-chainname-.c89f2475ee75630958e7500a6557c3a4':
      'Switch to {{chainName}} to Burn',
    'processing-please-do.208984b055f6471dd23be188b8cf00bb':
      'Processing, Please Do Not Close This Page',
    'automator-name.c5390787cd4e2753e3ba03ca7d750b87': 'Automator Name',
    'this-field-is-requir.387506720ffe25497994f087b0005620':
      'This field is required',
    'redemption-waiting-p.ac5cddc4e13f9fd24806a044fa7731dc':
      'Redemption Waiting Period',
    'the-redemption-waiti.a0e50c10565491c97cb618c8bc720620':
      'The Redemption Waiting Period refers to the time users must wait after submitting a redemption request for their funds to become claimable. Additionally, this period determines the maximum expiration date range for options tradable by the Automator manager.',
    'note-you-can-only-ex.c4eb0e13144659abfb4e6d559b6ac44c':
      'Note: You can only execute underlying products with expiry dates shorter or equal to the redemption period.',
    'profit-share-.36988bdb9234ac9be9f59c59863418c8': 'Profit Share %',
    'the-profits-share-ra.79616d4ba4fa6467eee8d4f7a22b6e3d':
      'The Profits Share Ratio defines the percentage of user profits that the Automator manager can share as their performance fee. If the Automator generates losses, the shared profits are recorded as negative until the account balance turns positive again. Only then can the manager resume withdrawing profit shares.',
    'automator-risk-level.8c44b6994ae1dcf58723f56799f0b79a':
      'Automator Risk Level',
    'the-maximum-percenta.13e4880a9c7cf7565c11dcffef4f9bd6':
      'The maximum percentage of your Automator capital you can lose.',
    'max-risk-exposure.c6597738c4babf5200d8d1c9b4738a87': 'Max Risk Exposure',
    'strategy-description.74321b00d1f36371e178bec81d30ff6a':
      'Strategy Description (Optional)',
    'switch-to-chainname-.659588b1c3541a1d3d13cf792069c73f':
      'Switch to {{chainName}} to Deploy',
    'deploy-automator-vau.dc5c36f8a73f7ad3aa3f19d9a1d72d95':
      'Deploy Automator Vault',
    'note-automator-vault.0f1828a2c02421b272568c78307710a6':
      'Note: Automator vault information cannot be modified after creation.',
    'automator-name-is-cr.5417504e22305f65d23e2cf7af38f1ba':
      'Automator [[{{name}}]] is Creating',
    'copy-successful.d819440c6b50319c681539684eacfd75': 'Copy successful',
    'automator-name-is-cr.f96ebcb85f8fdc824911cb82690ef842':
      'Automator [[{{name}}]] is created!',
    'go-to-automator-mana.ca2b1269e9775f02348aa7a5a77dbb99':
      'Go to Automator Management',
    'create-your-automato.a65e271e5fd255f45be39a4b81cb71ae':
      'Create Your Automator',
    'automator-chain.f61a1dec3d9e618b0d8b61abc759bf10': 'Automator Chain',
    'deposit-token.3e4608658a87e5eef3991e1a445019ae': 'Deposit Token',
    'step-.7e5270a3631f80f69cfada37222bd673': 'Step 1',
    'burn-amount-rch.e335a48ec3219b51d5ddf80b8235aadd': 'Burn {{amount}} RCH',
    'step-.40a730cf933151825b670df8c38a999e': 'Step 2',
    'deploy-automator-con.f41d4686ef62017003f2d0dcd2f1c7a1':
      'Deploy Automator Contract',
    'ethereum-mainnet.f86ed9470e319c17c2df8104d4d37c61': 'Ethereum Mainnet',
    'how-does-automator-w.b3192e4227fc06502db2be7ac9367277':
      'How does Automator work?',
    'automator-involves-t.d90ff34a99c7d9d2e79701b0cc8c8e9a':
      'Automator involves three key participants: <b>Users</b>, <b>Optivisors</b>, and <b>Market Makers</b>.\n\n1. <b>Users</b>\nUsers can select their preferred Automator and deposit tokens. Under the Optivisor’s expertise, the Automator generates returns, which are distributed among participating users. Additionally, users benefit from incentive $RCH token airdrops as part of their participation.\n\n2. <b>Optivisors</b>\nOptivisors are responsible for creating Automators and executing trading strategies—such as bullish and bearish positions—by interacting with SOFA Vaults. As a reward f inor their expertise, Optivisors earn a share of the profits.\n\n3. <b>Market Makers</b>\nSimilar to other SOFA products, Market Makers provide pricing for SOFA Vaults. Optivisors managers leverage these quotes to allocate Automator funds and participate in SOFA Vault strategies. Once these strategies are settled, profits are distributed accordingly.\nAutomator is an evolution of the SOFA protocol, offering a streamlined and cost-efficient way for users to participate while maximizing their potential returns.',
    'what-fees-will-i-be-.c0ea5261fda0d82f7bd246427d86603e':
      'What fees will I be charged?',
    'the-protocol-charges.b3763779a281274701b58a9ff10a9911':
      'The protocol charges a 15% service fee on the profits generated by Automators. If no profit is generated, no service fees are charged.\n\nOptivisors can also set a management fee when creating an Automator. This fee applies only to profits but is recorded as a liability during periods of losses. <b>The Optivisor can only collect management fees again once the Automator’s cumulative profits turn positive.</b>',
    'how-to-become-an-opt.f38afc0e65e76a7865e4a2596d0c996e':
      'How to become an Optivisor and create an Automator?',
    'anyone-can-create-an.2ff7d49775b43a6272816c79661c37d3':
      'Anyone can create an Automator as an Optivisor. However, each address is limited to creating one Automator per chain and deposit token type. To unlock the strategy quota, the Optivisor must burn {{burnAmount}} $RCH tokens.',
    'how-about-the-gas-fe.3a59b568e7713c86ceeae954523f7452':
      'How about the gas fees within the Automator?',
    'the-optivisor-is-res.d1e602ea19eeee5b69f2522ebf7051d0':
      'The Optivisor is responsible for covering all gas fees related to transactions executed within the Automator.',
    'how-can-i-withdraw-m.ff5f8c4f9eccdb2bdc508c33a8a9edfc':
      'How can I withdraw my funds after depositing into an Automator?',
    'automators-operate-s.e22250163128665834c45e97bad6fff1':
      "Automators operate similarly to funds, incorporating a redemption lock-up period to manage liquidity and ensure effective strategy execution. You can initiate a withdrawal at any time, but you must wait for the <u>Redemption Lock-up period</u> to end before completing the <b>Claim</b> process.\n\nThe redemption lock-up period is determined by the Optivisor during the Automator's creation and can vary based on the specific setup, with a maximum duration of 30 days.",
    'what-kinds-of-return.07b339bcbbee37f702dac1db4d7165d5':
      'What kinds of returns can I expect with an Automator?',
    'automator-returns-ar.f4c588fe6b0ca5e12806e8334e67c8ca':
      'Automator returns are composed of three key components:\n\n1. <b>Interest</b>\n- Funds deposited into the Automator are automatically staked in low-risk protocols like Aave or Curve, generating passive interest.\n- These returns are updated in real-time and distributed to users based on their share when withdrawing.\n\n2. <b>Trading PNL</b>\n- Returns generated from the Optivisor’s trading strategies\n- These returns are reflected only after the trading strategy expires, allowing the Optivisor to claim the positions. Users receive their share upon withdrawal.\n\n3. <b>$RCH incentive</b>\n- $RCH token airdrops earned through the Optivisor’s trading activities.\n- Airdrops are distributed daily based on the current holders of the Automator and their respective ownership shares. Users can claim their $RCH tokens directly from the Claim $RCH page.',
    'what-are-the-risks-a.919a5bf8fbd259e8911621222e7f6b74':
      'What are the risks associated with using an Automator?',
    'automator-involves-r.25e7c54a33b6ce14fc05355b3f720360':
      'Automator involves risks, as the Optivisor manages the funds deposited by users to execute options trading strategies and allocate them to low-risk protocols for earning interest. The Optivisor’s decisions play a crucial role in shaping the Automator’s risk and return profile.\n\nSpecifically, the Optivisor decides how to allocate funds between generating returns in low-risk protocols and using either the interest earned or the principal for options trading. The higher the proportion of principal allocated to options trading—rather than relying primarily on interest earnings—the greater the associated risk.\n\nWhen creating an Automator, Optivisors must set a buffer limit for the total funds they manage. For example, if the buffer is set at 10%, the Optivisor can use up to 90% of the total pool for options trading. This buffer acts as a safeguard and ensures disciplined fund allocation. Users can see this buffer percentage for each Automator, enabling them to choose based on their risk preferences—different buffers reflect different risk levels.\n\nSOFA does not enforce risk-free trading, and there is a possibility of losing your principal depending on the Optivisor’s chosen strategy. Please evaluate your risk tolerance carefully before participating and proceed with caution.',
    'how-is-the-rch-airdr.2ea2979fc26fddc6add59ed9baf89153':
      "How is the $RCH airdrop generated and distributed to user's account?",
    '-rch-tokens-are-earn.be550c2b0d03d8d32ef1937b3010d587':
      '$RCH tokens are earned through the Optivisor\'s trading activities and can be claimed by users afterward, just like in other SOFA Vaults. You can check the $RCH airdrop info here: <a target="_blank" href="https://docs.sofa.org/tokenomics/">https://docs.sofa.org/tokenomics/</a>',
    'you-have-already-cre.951777691328d6577a10b3c196e0dd3a':
      'You have already created an Automator contract "{{existingAutomatorName}}" with the selected deployed chain and deposit token.',
    'create-your-automato.fb859e7bec5b5c9760f3a035058a20e2':
      'Create Your Automator Strategies',
    'automator-chain.ea321b5387a11071de5f9a54ac293ef1': 'Automator Chain',
    'select.8b18f93877adf93fc9972cced9ffc4e4': 'Select',
    'please-select-automa.48ee3fa67503167dc2650fbc953c9fd3':
      'Please select Automator Chain first',
    'please-select-automa.cb40d7370edcb554f25f503601db4acd':
      'Please select Automator Chain',
    'please-select-deposi.dfb2bf7ff300358df65e3b78c2e943b7':
      'Please select Deposit Token',
    'connect-wallet.4b176925d8ee40dff9ca79658826418b': 'Connect Wallet',
    'burn-rch-create-your.5053e31cbcbb962d5930098a270c280b':
      'Burn RCH & Create Your Automator',
    'note-each-wallet-add.24a9df42c0d802f4d70941c9437bafbe':
      'Note: Each wallet address can only create one Automator with the same deposit token per chain.',
    'zero-trading-fees.5f13db0bf7d33d9321ff1635333a4a70': 'Zero Trading Fees',
    'enjoy-trading-fees-w.eef4f5c2087b655b5a2cc54def31e7d6':
      'Enjoy 0 trading fees when executing trades through your AutoMator.',
    'profits-sharing.5b5a51969697aaf0e017b97b064e7d95': 'Profits Sharing',
    'enjoy-up-to-in-profi.d897c9e6fd7e2850c914b243e9e28a05':
      'Enjoy up to 15% in profit sharing from your Automator subscribers.',
    'earn-hassle-free-int.f42835f7050b531bb4fb87b5867f82c5':
      'Earn Hassle-Free Interest',
    'funds-in-your-automa.a2d2d8f386512cd2fedf0f14571931d8':
      'Funds in your Automator will grow passively through AAVE/CRV, enjoying riskfree-like returns.',
    'faq.2cdc419517e40c76b856c005e76356bf': 'FAQ',
  },
  'zh-CN': {
    'confirm-to-burn.cae2f657407bcc9c793c957b87edf312': '确认销毁',
    'switch-to-chainname-.c89f2475ee75630958e7500a6557c3a4':
      '切换到{{chainName}}进行销毁',
    'processing-please-do.208984b055f6471dd23be188b8cf00bb':
      '处理中，请勿关闭此页面',
    'automator-name.c5390787cd4e2753e3ba03ca7d750b87': 'Automator名称',
    'this-field-is-requir.387506720ffe25497994f087b0005620': '此字段为必填项',
    'redemption-waiting-p.ac5cddc4e13f9fd24806a044fa7731dc': '赎回等待期',
    'the-redemption-waiti.a0e50c10565491c97cb618c8bc720620':
      '赎回等待期指用户提交赎回请求后，需等待的时间才能认领其资金。此外，该期限还规定了由Automator经理交易的期权的最大到期日期范围。',
    'note-you-can-only-ex.c4eb0e13144659abfb4e6d559b6ac44c':
      '注意：您只能交易到期日期在选择的等待期内的产品。',
    'profit-share-.36988bdb9234ac9be9f59c59863418c8': '利润分成百分比',
    'the-profits-share-ra.79616d4ba4fa6467eee8d4f7a22b6e3d':
      '利润分成比例定义了Automator经理可共享的用户利润百分比，作为其绩效费用。如果Automator产生亏损，共享利润记录为负，直到账户余额再次变为正数，此时经理才可继续提取利润分成。',
    'automator-risk-level.8c44b6994ae1dcf58723f56799f0b79a':
      'Automator风险级别',
    'the-maximum-percenta.13e4880a9c7cf7565c11dcffef4f9bd6':
      '您Automator资本的最大可损失百分比。',
    'max-risk-exposure.c6597738c4babf5200d8d1c9b4738a87': '最大风险敞口',
    'strategy-description.74321b00d1f36371e178bec81d30ff6a': '策略描述 (可选)',
    'switch-to-chainname-.659588b1c3541a1d3d13cf792069c73f':
      '切换到{{chainName}}进行部署',
    'deploy-automator-vau.dc5c36f8a73f7ad3aa3f19d9a1d72d95':
      '部署Automator金库',
    'note-automator-vault.0f1828a2c02421b272568c78307710a6':
      '注意：创建金库后，Automator信息不可编辑。',
    'automator-name-is-cr.5417504e22305f65d23e2cf7af38f1ba':
      'Automator [[{{name}}]]正在创建',
    'copy-successful.d819440c6b50319c681539684eacfd75': '复制成功',
    'automator-name-is-cr.f96ebcb85f8fdc824911cb82690ef842':
      'Automator [[{{name}}]]已创建！',
    'go-to-automator-mana.ca2b1269e9775f02348aa7a5a77dbb99':
      '前往 Automator 管理',
    'create-your-automato.a65e271e5fd255f45be39a4b81cb71ae': '创建Automator',
    'automator-chain.f61a1dec3d9e618b0d8b61abc759bf10': 'Automator链',
    'deposit-token.3e4608658a87e5eef3991e1a445019ae': '存入代币',
    'step-.7e5270a3631f80f69cfada37222bd673': '步骤1',
    'burn-amount-rch.e335a48ec3219b51d5ddf80b8235aadd': '燃烧{{amount}} RCH',
    'step-.40a730cf933151825b670df8c38a999e': '步骤2',
    'deploy-automator-con.f41d4686ef62017003f2d0dcd2f1c7a1':
      '部署Automator合约',
    'ethereum-mainnet.f86ed9470e319c17c2df8104d4d37c61': '以太坊主网',
    'how-does-automator-w.b3192e4227fc06502db2be7ac9367277':
      'Automator 是如何工作的?',
    'automator-involves-t.d90ff34a99c7d9d2e79701b0cc8c8e9a':
      'Automator 涉及三大主要参与者：<b>用户</b>、<b>Optivisors</b>和<b>做市商</b>。\n\n1. <b>用户</b>\n用户可以选择自己喜欢的 Automator 并存入代币。在 Optivisor 的专业指导下，Automator 产生收益，并分配给参与的用户。此外，用户还可以通过参与获得 $RCH 激励代币空投。\n\n2. <b>Optivisors</b>\nOptivisors 负责创建 Automator 并通过与 SOFA Vaults 的互动执行交易策略——如看涨和看跌仓位。作为对他们专业知识的奖励，Optivisors 可以分享一部分利润。\n\n3. <b>做市商</b>\n与其他 SOFA 产品类似，做市商为 SOFA Vaults 提供定价。Optivisors 管理者利用这些报价分配 Automator 资金并参与 SOFA Vaults 策略。一旦这些策略结算，利润将按比例分配。\nAutomator 是 SOFA 协议的发展，提供了一种简化且成本效益高的方式，使用户在最大化潜在收益的同时参与其中。',
    'what-fees-will-i-be-.c0ea5261fda0d82f7bd246427d86603e':
      '我会被收取哪些费用?',
    'the-protocol-charges.b3763779a281274701b58a9ff10a9911':
      '该协议对 Automator 产生的利润收取 15% 的服务费。如果没有产生利润，则不收取服务费。\n\nOptivisors 在创建 Automator 时还可以设定管理费。该费用仅适用于利润，但在亏损期间记录为负债。<b>Optivisor 只有在 Automator 的累计利润转为正数后才能再次收取管理费。</b>',
    'how-to-become-an-opt.f38afc0e65e76a7865e4a2596d0c996e':
      '如何成为 Optivisor 并创建 Automator?',
    'anyone-can-create-an.2ff7d49775b43a6272816c79661c37d3':
      '任何人都可以作为 Optivisor 创建一个 Automator。然而，每个地址在每条链和每种存入代币类型上只能创建一个 Automator。要解锁策略限额，Optivisor 必须燃烧 {{burnAmount}} $RCH 代币。',
    'how-about-the-gas-fe.3a59b568e7713c86ceeae954523f7452':
      'Automator 内部的 Gas 费用如何?',
    'the-optivisor-is-res.d1e602ea19eeee5b69f2522ebf7051d0':
      'Optivisor 负责覆盖在 Automator 内执行交易相关的所有 Gas 费用。',
    'how-can-i-withdraw-m.ff5f8c4f9eccdb2bdc508c33a8a9edfc':
      '将资金存入 Automator 后，我如何提现?',
    'automators-operate-s.e22250163128665834c45e97bad6fff1':
      'Automator 的运行方式类似于基金，采用赎回锁定期来管理流动性并确保策略的有效执行。您可以随时提出提现，但您必须等到<u>赎回锁定期</u>结束后才可完成<b>领取</b>过程。\n\n赎回锁定期由 Optivisor 在创建 Automator 时决定，具体时间可能会因具体设置而有所不同，最长为 30 天。',
    'what-kinds-of-return.07b339bcbbee37f702dac1db4d7165d5':
      '使用 Automator 时可以期望什么样的回报?',
    'automator-returns-ar.f4c588fe6b0ca5e12806e8334e67c8ca':
      'Automator 的回报由三个关键部分组成：\n\n1. <b>利息</b>\n- 存入 Automator 的资金会自动质押在 Aave 或 Curve 等低风险协议中，产生被动利息。\n- 这些收益会实时更新，并在用户提现时根据其份额分配给他们。\n\n2. <b>交易盈亏</b>\n- 通过 Optivisor 的交易策略产生的收益\n- 这些收益只有在交易策略到期后才会反映出来，Optivisor 可以认领仓位。用户在提现时会收到他们的份额。\n\n3. <b>$RCH 激励</b>\n- 通过 Optivisor 的交易活动赚取的 $RCH 代币空投。\n- 空投按 Automator 当前持有者及其相应持有份额每日分发。用户可以直接从 领取 $RCH 页面领取他们的 $RCH 代币。',
    'what-are-the-risks-a.919a5bf8fbd259e8911621222e7f6b74':
      '使用 Automator 存在哪些风险?',
    'automator-involves-r.25e7c54a33b6ce14fc05355b3f720360':
      'Automator 存在风险，因为 Optivisor 管理用户存入的资金以执行期权交易策略，并将其分配到低风险协议中以赚取利息。Optivisor 的决策在塑造 Automator 的风险和回报配置中起着关键作用。\n\n具体而言，Optivisor 决定如何分配资金在生成低风险协议的收益和选择使用赚取的利息或本金进行期权交易之间。分配更高比例的本金进行期权交易而不是主要依赖利息收益，会增加相关风险。\n\n创建 Automator 时，Optivisors 必须为其管理的总资金设定一个缓冲限额。例如，如果缓冲设定为 10%，Optivisor 最多可以使用 90% 的总池资金进行期权交易。这个缓冲作为一种安全措施，确保了资金分配的纪律性。用户可以看到每个 Automator 的缓冲百分比，从而根据其风险偏好选择——不同的缓冲反映不同的风险水平。\n\nSOFA 不强制进行无风险交易，Optivisor 选择的策略可能会导致您损失本金。请仔细评估您的风险承受能力，在参与之前谨慎行事。',
    'how-is-the-rch-airdr.2ea2979fc26fddc6add59ed9baf89153':
      '$RCH 代币空投如何生成并分发到用户账户?',
    '-rch-tokens-are-earn.be550c2b0d03d8d32ef1937b3010d587':
      '$RCH 代币通过 Optivisor 的交易活动赚取，随后用户可认领，类似于其他 SOFA Vaults。您可以在这里查看 $RCH 空投信息：<a target="_blank" href="https://docs.sofa.org/tokenomics/">https://docs.sofa.org/tokenomics/</a>',
    'you-have-already-cre.951777691328d6577a10b3c196e0dd3a':
      '您已基于所选的已部署链和存款代币创建了 "{{existingAutomatorName}}" Automator 合约。',
    'create-your-automato.fb859e7bec5b5c9760f3a035058a20e2':
      '创建你 Automator 策略',
    'automator-chain.ea321b5387a11071de5f9a54ac293ef1': 'Automator 链',
    'select.8b18f93877adf93fc9972cced9ffc4e4': '选择',
    'please-select-automa.48ee3fa67503167dc2650fbc953c9fd3':
      '请先选择 Automator 链',
    'please-select-automa.cb40d7370edcb554f25f503601db4acd':
      '请选择 Automator 链',
    'please-select-deposi.dfb2bf7ff300358df65e3b78c2e943b7': '请选择存入代币',
    'connect-wallet.4b176925d8ee40dff9ca79658826418b': '连接钱包',
    'burn-rch-create-your.5053e31cbcbb962d5930098a270c280b':
      '燃烧 RCH 并创建您的 Automator',
    'note-each-wallet-add.24a9df42c0d802f4d70941c9437bafbe':
      '注意：每个钱包地址在每条链和每种存入代币组合上只能创建一个 Automator。',
    'zero-trading-fees.5f13db0bf7d33d9321ff1635333a4a70': '零交易费用',
    'enjoy-trading-fees-w.eef4f5c2087b655b5a2cc54def31e7d6':
      '通过AutoMator交易享受零交易费用。',
    'profits-sharing.5b5a51969697aaf0e017b97b064e7d95': '分享利润',
    'enjoy-up-to-in-profi.d897c9e6fd7e2850c914b243e9e28a05':
      '通过订阅您AutoMator的用户可赚取高达15%的利润分成。',
    'earn-hassle-free-int.f42835f7050b531bb4fb87b5867f82c5': '赚取无风险利息',
    'funds-in-your-automa.a2d2d8f386512cd2fedf0f14571931d8':
      '您在AutoMator中的资金通过AAVE/CRV被动增长，赚取稳定的无风险回报。',
    'faq.2cdc419517e40c76b856c005e76356bf': '常见问题',
  },
};
