export default {
  'en-US': {
    'The SOFA protocols were developed as a transparent and open-source effort, with maximum security and safety of assets at the top of mind.  However, unforeseen and "force majeure" risks are always a remote possibility, and users shall explicitly acknowledge and accept full responsibility for any adverse outcomes that might arise from their activities on the SOFA protocols.':
      'The SOFA protocols were developed as a transparent and open-source effort, with maximum security and safety of assets at the top of mind.  However, unforeseen and "force majeure" risks are always a remote possibility, and users shall explicitly acknowledge and accept full responsibility for any adverse outcomes that might arise from their activities on the SOFA protocols.',
    "<b>1.Payoff Variability & Losses</b>\n· Surge-based products are prone to full capital losses as a result of unfavourable market outcomes.\n· Earn-based products could see fluctuations in realized yields from external factors, such as changes in Aave/Lido's prevailing interest rates.\n\n<b>2.DeFi Extensibility Risks with External Protocols</b>\n· SOFA protocols are fully extensible with 3rd party DeFi projects beyond our control, and exploits to these external protocols could bring unforeseen negative impact.\n\n<b>3.Staking Yield Deficit</b>\n· A short-fall in staking income from Aave/Lido (extreme case = 0%) could cause Earn-based products to return a total payout that is slightly less than the original deposit.\n\n<b>4.Blockchain Systemic Risks</b>\n· SOFA protocols are reliant on Ethereum and EVM-compatible L1s/L2s for overall network and asset security.\n\n<b>5.Smart Contract Code Integrity</b>\n· The SOFA protocols have passed a full chain audit from {{auditAgent}} as of {{time}}.\n":
      "<b>1.Payoff Variability & Losses</b>\n· Surge-based products are prone to full capital losses as a result of unfavourable market outcomes.\n· Earn-based products could see fluctuations in realized yields from external factors, such as changes in Aave/Lido's prevailing interest rates.\n\n<b>2.DeFi Extensibility Risks with External Protocols</b>\n· SOFA protocols are fully extensible with 3rd party DeFi projects beyond our control, and exploits to these external protocols could bring unforeseen negative impact.\n\n<b>3.Staking Yield Deficit</b>\n· A short-fall in staking income from Aave/Lido (extreme case = 0%) could cause Earn-based products to return a total payout that is slightly less than the original deposit.\n\n<b>4.Blockchain Systemic Risks</b>\n· SOFA protocols are reliant on Ethereum and EVM-compatible L1s/L2s/ L2s for overall network and asset security.\n\n<b>5.Smart Contract Code Integrity</b>\n· The SOFA protocols have passed a full chain audit from {{auditAgent}} as of {{time}}.\n",
    'june-.cef78107665ef3fe7427225cd6ee81a6': 'June 2024',
  },
  'ja-JP': {
    'The SOFA protocols were developed as a transparent and open-source effort, with maximum security and safety of assets at the top of mind.  However, unforeseen and "force majeure" risks are always a remote possibility, and users shall explicitly acknowledge and accept full responsibility for any adverse outcomes that might arise from their activities on the SOFA protocols.':
      'SOFAプロトコルは、資産の最大限のセキュリティと安全性を最優先に考慮して、透明でオープンソースの努力として開発されました。しかし、予測不能なリスクや「不可抗力」のリスクは常に存在する可能性があり、ユーザーはSOFAプロトコルでの活動によって生じる可能性のある不利な結果について、明確に認識し、全責任を受け入れるべきです。',
    "<b>1.Payoff Variability & Losses</b>\n· Surge-based products are prone to full capital losses as a result of unfavourable market outcomes.\n· Earn-based products could see fluctuations in realized yields from external factors, such as changes in Aave/Lido's prevailing interest rates.\n\n<b>2.DeFi Extensibility Risks with External Protocols</b>\n· SOFA protocols are fully extensible with 3rd party DeFi projects beyond our control, and exploits to these external protocols could bring unforeseen negative impact.\n\n<b>3.Staking Yield Deficit</b>\n· A short-fall in staking income from Aave/Lido (extreme case = 0%) could cause Earn-based products to return a total payout that is slightly less than the original deposit.\n\n<b>4.Blockchain Systemic Risks</b>\n· SOFA protocols are reliant on Ethereum and EVM-compatible L1s/L2s for overall network and asset security.\n\n<b>5.Smart Contract Code Integrity</b>\n· The SOFA protocols have passed a full chain audit from {{auditAgent}} as of {{time}}.\n":
      '<b>1.支払い変動性と損失</b>\n· Surgeベースの製品は、市場の不利な結果により全額の資本損失が生じる可能性があります。\n· Earnベースの製品は、Aave/Lidoの利率変動などの外部要因による実際の収益の変動が見られることがあります。\n\n<b>2.DeFiの拡張性に関するリスク</b>\n· SOFAプロトコルは、私たちの管理を超えたサードパーティーDeFiプロジェクトと完全に互換性があり、このような外部プロトコルへの攻撃が予想外のマイナスの影響をもたらすことがあります。\n\n<b>3.ステーキング収益不足</b>\n・Aave/Lidoからのステーキング収入の不足（極端な場合は0％）は、Earnベースの製品で元の預金よりも少し少ない合計支払いをもたらすことがあります。\n\n<b>4.ブロックチェーンシステムのリスク</b>\n・SOFAプロトコルは、全体的なネットワークと資産の安全性のため、EthereumおよびEVM互換のL1/L2に依存しています。\n\n<b>5.スマートコントラクトコードの完整性</b>\n・SOFAプロトコルは{{auditAgent}}によるフルチェーン監査を{{time}}までに通過しています。',
    'june-.cef78107665ef3fe7427225cd6ee81a6': '2024年6月',
  },
  'ru-RU': {
    'The SOFA protocols were developed as a transparent and open-source effort, with maximum security and safety of assets at the top of mind.  However, unforeseen and "force majeure" risks are always a remote possibility, and users shall explicitly acknowledge and accept full responsibility for any adverse outcomes that might arise from their activities on the SOFA protocols.':
      'Протоколы SOFA были разработаны как прозрачное и открытое решение, с максимальной безопасностью и сохранностью активов в приоритете. Однако непредвиденные риски и риски "форс-мажор" всегда являются отдаленной возможностью, и пользователи должны ясно осознавать и полностью принимать ответственность за любые неблагоприятные последствия, которые могут возникнуть в результате их действий на протоколах SOFA.',
    "<b>1.Payoff Variability & Losses</b>\n· Surge-based products are prone to full capital losses as a result of unfavourable market outcomes.\n· Earn-based products could see fluctuations in realized yields from external factors, such as changes in Aave/Lido's prevailing interest rates.\n\n<b>2.DeFi Extensibility Risks with External Protocols</b>\n· SOFA protocols are fully extensible with 3rd party DeFi projects beyond our control, and exploits to these external protocols could bring unforeseen negative impact.\n\n<b>3.Staking Yield Deficit</b>\n· A short-fall in staking income from Aave/Lido (extreme case = 0%) could cause Earn-based products to return a total payout that is slightly less than the original deposit.\n\n<b>4.Blockchain Systemic Risks</b>\n· SOFA protocols are reliant on Ethereum and EVM-compatible L1s/L2s for overall network and asset security.\n\n<b>5.Smart Contract Code Integrity</b>\n· The SOFA protocols have passed a full chain audit from {{auditAgent}} as of {{time}}.\n":
      '<b>1.Вариативность выплат и потери</b>\n· Продукты на базе Surge подвержены полной потере капитала из-за неблагоприятных исходов на рынке.\n· Продукты на базе Earn могут испытывать колебания реализованных доходов из-за внешних факторов, таких как изменения ставок по депозитам Aave/Lido.\n\n<b>2.Риски расширяемости DeFi с внешними протоколами</b>\n· Протоколы SOFA полностью расширяемы за счет сторонних DeFi проектов, находящихся вне нашего контроля, и взлом этих внешних протоколов может привести к непредвиденному негативному влиянию.\n\n<b>3.Дефицит дохода от стейкинга</b>\n· Недостаток дохода от стейкинга в Aave/Lido (в крайнем случае = 0%) может привести к тому, что продукты на базе Earn вернут общую выплату, которая будет немного меньше первоначального депозита.\n\n<b>4.Системные риски блокчейна</b>\n· Протоколы SOFA зависят от Ethereum и совместимых с EVM L1s/L2s/ L2s для обеспечения общей сетевой и имущественной безопасности.\n\n<b>5.Целостность кода смарт-контракта</b>\n· Протоколы SOFA прошли полный аудит цепочки от {{auditAgent}} на момент {{time}}.\n',
    'june-.cef78107665ef3fe7427225cd6ee81a6': 'Июнь 2024 года',
  },
  'zh-CN': {
    'The SOFA protocols were developed as a transparent and open-source effort, with maximum security and safety of assets at the top of mind.  However, unforeseen and "force majeure" risks are always a remote possibility, and users shall explicitly acknowledge and accept full responsibility for any adverse outcomes that might arise from their activities on the SOFA protocols.':
      'SOFA协议是以透明和开源的方式开发的，始终将资产的安全性放在首位。然而，不可预见的風險以及“不可抗力”事件仍有可能性，用户需明确知晓并接受因在SOFA协议上进行活动而可能产生的任何不利后果的全部责任。',
    "<b>1.Payoff Variability & Losses</b>\n· Surge-based products are prone to full capital losses as a result of unfavourable market outcomes.\n· Earn-based products could see fluctuations in realized yields from external factors, such as changes in Aave/Lido's prevailing interest rates.\n\n<b>2.DeFi Extensibility Risks with External Protocols</b>\n· SOFA protocols are fully extensible with 3rd party DeFi projects beyond our control, and exploits to these external protocols could bring unforeseen negative impact.\n\n<b>3.Staking Yield Deficit</b>\n· A short-fall in staking income from Aave/Lido (extreme case = 0%) could cause Earn-based products to return a total payout that is slightly less than the original deposit.\n\n<b>4.Blockchain Systemic Risks</b>\n· SOFA protocols are reliant on Ethereum and EVM-compatible L1s/L2s for overall network and asset security.\n\n<b>5.Smart Contract Code Integrity</b>\n· The SOFA protocols have passed a full chain audit from {{auditAgent}} as of {{time}}.\n":
      '<b>1.收益变动性和损失风险</b>\n· 基于Surge的产品可能因不利的市场结果而导致全部本金损失。\n· 基于Earn的产品可能会因外部因素(如 Aave/Lido 当前的利率变动)，而导致实际收益波动。\n\n<b>2.与外部协议相关的去DeFi扩展性风险</b>\n· SOFA协议可与我们无法控制的第三方DeFi项目完全兼容，这些外部协议的漏洞可能带来不可预见的负面影响。\n\n<b>3.质押收益不足</b>\n· 来自 Aave/Lido 的质押收入不足（极端情况下为0%）可能导致基于Earn产品的总收益略低于原始存款。\n\n<b>4.区块链系统性风险</b>\n· SOFA协议依赖以太坊和兼容EVM的L1和L2公链来确保整体网络和资产安全。\n\n<b>5.智能合约代码完整性</b>\n· 截至{{time}}，SOFA协议已通过{{auditAgent}}的链上审计。\n',
    'june-.cef78107665ef3fe7427225cd6ee81a6': '2024年6月',
  },
  'zh-HK': {
    'The SOFA protocols were developed as a transparent and open-source effort, with maximum security and safety of assets at the top of mind.  However, unforeseen and "force majeure" risks are always a remote possibility, and users shall explicitly acknowledge and accept full responsibility for any adverse outcomes that might arise from their activities on the SOFA protocols.':
      'SOFA協議是以透明和開源的方式開發的，始終將資產的安全性放在首位。然而，不可預見的風險以及「不可抗力」事件仍有可能性，用戶需明確知悉並接受因在SOFA協議上進行活動而可能產生的任何不利後果的全部責任。',
    "<b>1.Payoff Variability & Losses</b>\n· Surge-based products are prone to full capital losses as a result of unfavourable market outcomes.\n· Earn-based products could see fluctuations in realized yields from external factors, such as changes in Aave/Lido's prevailing interest rates.\n\n<b>2.DeFi Extensibility Risks with External Protocols</b>\n· SOFA protocols are fully extensible with 3rd party DeFi projects beyond our control, and exploits to these external protocols could bring unforeseen negative impact.\n\n<b>3.Staking Yield Deficit</b>\n· A short-fall in staking income from Aave/Lido (extreme case = 0%) could cause Earn-based products to return a total payout that is slightly less than the original deposit.\n\n<b>4.Blockchain Systemic Risks</b>\n· SOFA protocols are reliant on Ethereum and EVM-compatible L1s/L2s for overall network and asset security.\n\n<b>5.Smart Contract Code Integrity</b>\n· The SOFA protocols have passed a full chain audit from {{auditAgent}} as of {{time}}.\n":
      '<b>1.收益變動性和損失風險</b>\n· 基於Surge的產品可能因不利的市場結果而導致全部本金損失。\n· 基於Earn的產品可能會因外部因素（如Aave/Lido當前的利率變動）而導致實際收益波動。\n\n<b>2.與外部協議相關的去DeFi擴展性風險</b>\n· SOFA協議可與我們無法控制的第三方DeFi項目完全兼容，這些外部協議的漏洞可能帶來不可預見的負面影響。\n\n<b>3.質押收益不足</b>\n· 來自Aave/Lido的質押收入不足（極端情況下為0%）可能導致基於Earn產品的總收益略低於原始存款。\n\n<b>4.區塊鏈系統性風險</b>\n· SOFA協議依賴以太坊和兼容EVM的各級公鏈來確保整體網絡和資產安全。\n\n<b>5.智能合約代碼完整性</b>\n· 截至{{time}}，SOFA協議已通過{{auditAgent}}的全鏈審核。\n',
    'june-.cef78107665ef3fe7427225cd6ee81a6': '2024年6月',
  },
  'zh-TW': {
    'The SOFA protocols were developed as a transparent and open-source effort, with maximum security and safety of assets at the top of mind.  However, unforeseen and "force majeure" risks are always a remote possibility, and users shall explicitly acknowledge and accept full responsibility for any adverse outcomes that might arise from their activities on the SOFA protocols.':
      'SOFA協議是以透明和開源的方式開發的，始終將資產的安全性放在首位。然而，不可預見的風險以及「不可抗力」事件仍有可能性，用戶需明確知曉並接受因在SOFA協議上進行活動而可能產生的任何不利後果的全部責任。',
    "<b>1.Payoff Variability & Losses</b>\n· Surge-based products are prone to full capital losses as a result of unfavourable market outcomes.\n· Earn-based products could see fluctuations in realized yields from external factors, such as changes in Aave/Lido's prevailing interest rates.\n\n<b>2.DeFi Extensibility Risks with External Protocols</b>\n· SOFA protocols are fully extensible with 3rd party DeFi projects beyond our control, and exploits to these external protocols could bring unforeseen negative impact.\n\n<b>3.Staking Yield Deficit</b>\n· A short-fall in staking income from Aave/Lido (extreme case = 0%) could cause Earn-based products to return a total payout that is slightly less than the original deposit.\n\n<b>4.Blockchain Systemic Risks</b>\n· SOFA protocols are reliant on Ethereum and EVM-compatible L1s/L2s for overall network and asset security.\n\n<b>5.Smart Contract Code Integrity</b>\n· The SOFA protocols have passed a full chain audit from {{auditAgent}} as of {{time}}.\n":
      '<b>1.收益變動性和損失風險</b>\n· 基於Surge的產品可能因不利的市場結果而導致全部本金損失。\n· 基於Earn的產品可能會因外部因素(如 Aave/Lido 當前的利率變動)，而導致實際收益波動。\n\n<b>2.與外部協議相關的去DeFi擴展性風險</b>\n· SOFA協議可與我們無法控制的第三方DeFi項目完全兼容，這些外部協議的漏洞可能帶來不可預見的負面影響。\n\n<b>3.質押收益不足</b>\n· 來自 Aave/Lido 的質押收入不足（極端情況下為0%）可能導致基於Earn產品的總收益略低於原始存款。\n\n<b>4.區塊鏈系統性風險</b>\n· SOFA協議依賴以太坊和兼容EVM的L1s/L2s來確保整體網絡和資產安全。\n\n<b>5.智能合約代碼完整性</b>\n· 截至{{time}}，SOFA協議已通過{{auditAgent}}的鏈上審計。\n',
    'june-.cef78107665ef3fe7427225cd6ee81a6': '2024年6月',
  },
};
